# Generated by Django 5.1.1 on 2024-10-07 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("departments", "0003_historicaldepartment_position_historicalposition"),
        ("employees", "0007_alter_employee_position_and_more"),
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobposting",
            name="incharge_employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="employees.employee",
            ),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="position",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="departments.position",
            ),
        ),
    ]
