# Generated by Django 5.1.1 on 2024-10-15 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0008_document_approved_documentrequest"),
        ("jobs", "0002_jobposting_incharge_employee_jobposting_position"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="jobposting",
            name="filled",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="vacancies",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="candidateapplication",
            name="status",
            field=models.CharField(
                choices=[("Active", "Active"), ("Rejected", "Rejected")],
                default="Active",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="CandidateStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="employees.employee",
                    ),
                ),
                (
                    "candidate_application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stages",
                        to="jobs.candidateapplication",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="jobs.stage"
                    ),
                ),
            ],
        ),
    ]
