# Generated by Django 5.1.1 on 2024-10-15 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0008_document_approved_documentrequest"),
        ("jobs", "0004_stageset_jobposting_stage_set_stage_stage_set"),
    ]

    operations = [
        migrations.AddField(
            model_name="stage",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_stages",
                to="employees.employee",
            ),
        ),
    ]
