# Generated by Django 5.1.1 on 2024-10-15 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0005_stage_employee"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stage",
            name="employee",
        ),
    ]
