# Generated by Django 5.1.1 on 2024-10-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0007_candidatestage_result"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobposting",
            name="employment_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Full-Time", "Full-Time"),
                    ("Part-Time", "Part-Time"),
                    ("Contract", "Contract"),
                    ("Internship", "Internship"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
