# Generated by Django 5.1.1 on 2024-10-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0008_alter_jobposting_employment_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobposting",
            name="employment_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Full-Time", "full_time"),
                    ("Part-Time", "part_time"),
                    ("Contract", "contract"),
                    ("Internship", "internship"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
