# Generated by Django 5.1.1 on 2024-10-19 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0011_employeecontract"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EmployeeContract",
        ),
    ]
