# Generated by Django 5.1.1 on 2024-10-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0013_employeecontract"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeecontract",
            name="contract_start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
