# Generated by Django 5.1.1 on 2024-10-21 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0014_alter_employeecontract_contract_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeecontract",
            name="signed_contract",
            field=models.FileField(
                blank=True, null=True, upload_to="signed_contracts/"
            ),
        ),
    ]
