# Generated by Django 5.1.1 on 2024-10-06 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("departments", "0003_historicaldepartment_position_historicalposition"),
        ("employees", "0006_remove_employeejobdetails_joining_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="position",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="departments.position",
            ),
        ),
        migrations.AlterField(
            model_name="historicalemployee",
            name="position",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="departments.position",
            ),
        ),
    ]
