# Generated by Django 5.1.1 on 2024-10-19 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0008_document_approved_documentrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="status",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalemployee",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
